### ISSUE TITLE
Image For README.md

### ISSUE THREAD

**Issue by coffmark** [Ryosukekamimura/TimeApp#6]

**Comment by Ryosukekamimura** [comment]
![swift](https://user-images.githubusercontent.com/52638834/88453046-a238af80-ce9e-11ea-8efc-b9a2f4c76ca1.png)

**Comment by Ryosukekamimura** [comment]
![SwiftUI](https://user-images.githubusercontent.com/52638834/88453112-402c7a00-ce9f-11ea-86a4-185f9727d278.png)
![iPhone 11 Pro - 2020-07-25 at 13 13 56](https://user-images.githubusercontent.com/52638834/88453115-49b5e200-ce9f-11ea-9bff-2e82d5c5f8f8.png)
![iPhone 11 Pro - 2020-07-25 at 13 14 34](https://user-images.githubusercontent.com/52638834/88453118-4d496900-ce9f-11ea-8d50-a50863f563a1.png)

**Comment by Ryosukekamimura** [comment]
![database](https://user-images.githubusercontent.com/52638834/88453296-9ea62800-cea0-11ea-9cfd-2cd22e2e4d3a.png)

**Comment by Ryosukekamimura** [comment]
![Sunrise](https://user-images.githubusercontent.com/52638834/88453764-0b232600-cea5-11ea-89e0-a195116aadcc.jpg)

**Comment by Ryosukekamimura** [comment]
![Sunrise12](https://user-images.githubusercontent.com/52638834/88453856-c9df4600-cea5-11ea-9b43-0261168afa63.jpeg)

**Comment by Ryosukekamimura** [comment]
![Sunrise12](https://user-images.githubusercontent.com/52638834/88454350-f4cb9900-cea9-11ea-8b9a-22a184420309.jpeg)

**Comment by Ryosukekamimura** [comment]
![Sunrise12](https://user-images.githubusercontent.com/52638834/88454406-63a8f200-ceaa-11ea-857d-804d52791348.jpeg)

**Comment by Ryosukekamimura** [comment]
![Sunrise12](https://user-images.githubusercontent.com/52638834/88467675-722bf380-cf14-11ea-8ef4-52bc11fc5e7c.jpeg)

**Comment by Ryosukekamimura** [comment]
![Uploading IMG_4483.PNG…]()

**Comment by Ryosukekamimura** [comment]
![IMG_4482](https://user-images.githubusercontent.com/52638834/93875586-3349cc80-fd10-11ea-99ed-51705dff48c5.PNG)

**Comment by Ryosukekamimura** [comment]
![Uploading IMG_4483.PNG…]()

**Comment by Ryosukekamimura** [comment]
![IMG_4483](https://user-images.githubusercontent.com/52638834/93875622-48266000-fd10-11ea-85ea-a20fd0b4104b.PNG)

**Comment by Ryosukekamimura** [comment]
![IMG_B0E9D06DB02C-1](https://user-images.githubusercontent.com/52638834/101755705-89146080-3b18-11eb-9704-783a2d39cb86.jpeg)

**Comment by Ryosukekamimura** [comment]
![IMG_B0E9D06DB02C-1](https://user-images.githubusercontent.com/52638834/101755812-acd7a680-3b18-11eb-92ec-e3590bc2bd63.jpeg)
